Repository bitcoindevkit/bdk, pull requests merged in 2022-08, with the labels that each got.

#694 Add assertions in the FeeRate constructor
  src/types.rs
Labels: enhancement

#645 Allow signing only specific leaf hashes
  CHANGELOG.md
  src/wallet/mod.rs
  src/wallet/signer.rs
Labels: enhancement

#693 Fix the early InsufficientFunds error in the branch and bound
  src/wallet/coin_selection.rs
Labels: bug

#683 Fix wallet sync for `RpcBlockchain`
  CHANGELOG.md
  examples/rpcwallet.rs
  src/blockchain/rpc.rs
  src/testutils/blockchain_tests.rs
Labels: bug

#640 Get balance in categories
  CHANGELOG.md
  src/blockchain/electrum.rs
  src/blockchain/mod.rs
  src/testutils/blockchain_tests.rs
  src/testutils/configurable_blockchain_tests.rs
  src/types.rs
  src/wallet/mod.rs
Labels: enhancement

#704 Fix `rpc::CoreTxIter` logic.
  src/blockchain/rpc.rs
Labels: bug

#723 Fix P2WPKH_SATISFACTION_SIZE in CS tests
  src/wallet/coin_selection.rs
Labels: bug

#738 Fix docs.rs features
  Cargo.toml
  src/wallet/mod.rs
Labels: ci
