Repository bitcoindevkit/bdk, pull requests merged in 2022-09, with the labels that each got.

#708 Change configs for source-base code coverage
  .github/workflows/code_coverage.yml
  README.md
  codecov.yaml
Labels: ci

#728 Add fee_amount() and fee_rate() functions to PsbtUtils trait
  src/psbt/mod.rs
Labels: enhancement

#757 Enable signing taproot transactions with only `non_witness_utxos`
  src/wallet/mod.rs
  src/wallet/signer.rs
Labels: bug

#763 Fix `Wallet::descriptor_checksum` to actually return the checksum
  src/wallet/mod.rs
Labels: bug
