Repository bitcoindevkit/bdk, pull requests merged in 2022-07, with the labels that each got.

#652 Fix: Hang when `ElectrumBlockchainConfig::stop_gap == 0`
  CHANGELOG.md
  src/blockchain/electrum.rs
  src/blockchain/esplora/mod.rs
  src/blockchain/esplora/ureq.rs
  src/testutils/configurable_blockchain_tests.rs
  src/testutils/mod.rs
Labels: bug

#585 set coin type based on network
  CHANGELOG.md
  src/descriptor/template.rs
  src/wallet/mod.rs
Labels: enhancement

#648 test: BDK won't add unconf inputs when fee bumping
  src/database/memory.rs
  src/wallet/mod.rs
Labels: tests

#634 Get block hash by its height
  CHANGELOG.md
  src/blockchain/any.rs
  src/blockchain/compact_filters/mod.rs
  src/blockchain/electrum.rs
  src/blockchain/esplora/reqwest.rs
  src/blockchain/esplora/ureq.rs
  src/blockchain/mod.rs
  src/blockchain/rpc.rs
  src/testutils/blockchain_tests.rs
Labels: enhancement

#671 Introduce `get_checksum_bytes` method and improvements
  CHANGELOG.md
  src/descriptor/checksum.rs
  src/descriptor/error.rs
Labels: enhancement

#659 Fix: Run README.md examples on the CI
  README.md
  src/doctest.rs
Labels: documentation

#661 Test: No address reuse for single descriptor
  src/wallet/mod.rs
Labels: tests

#630 Move change logic to coin_select
  CHANGELOG.md
  src/wallet/coin_selection.rs
  src/wallet/mod.rs
Labels: enhancement
