Repository bitcoindevkit/bdk, pull requests merged in 2022-12, with the labels that each got.

#811 Downgrade ubuntu to 20.04 for test_hardware_wallet CI job
  .github/workflows/cont_integration.yml
Labels: ci

#822 Update ci nightly-docs workflow to use nightly-2022-12-14
  .github/workflows/nightly_docs.yml
Labels: ci

#820 Make README.md code examples compile without errors
  README.md
Labels: documentation

#808 fix: make save_tx order independent
  src/blockchain/electrum.rs
Labels: bug

#818 Fix wrong key origin path in public descriptor templates
  src/descriptor/template.rs
Labels: bug

#812 Implement ordering for TransactionDetails
  src/types.rs
Labels: enhancement

#805 electrum: add validate_domain to ElectrumBlockchainConfig
  src/blockchain/any.rs
  src/blockchain/electrum.rs
Labels: enhancement

#828 Bump version to 0.26.0
  Cargo.toml
Labels: release
