Repository bitcoindevkit/bdk, pull requests merged in 2023-02, with the labels that each got.

#838 Add small clarification to docs
  examples/compiler.rs
  src/descriptor/template.rs
  src/keys/mod.rs
  src/psbt/mod.rs
  src/types.rs
  src/wallet/mod.rs
Labels: documentation

#852 Bump version to 0.27.0
  CHANGELOG.md
  Cargo.toml
Labels: release

#863 Fix ci Dockerfile.ledger
  ci/Dockerfile.ledger
Labels: ci

#867 Update rusqlite from 0.27.0 to 0.28.0
  Cargo.toml
Labels: bug
