Repository bitcoindevkit/bdk, pull requests merged in 2023-11, with the labels that each got.

#1145 fix(electrum): fixed chain sync issue
  crates/electrum/src/electrum_ext.rs
Labels: bug

#1200 fix(bdk): Check if we're using the correct internal key before signing
  crates/bdk/src/wallet/signer.rs
  crates/bdk/tests/psbt.rs
Labels: bug

#1202 fix(chain): filter coinbase tx not in best chain
  crates/chain/src/tx_graph.rs
  crates/chain/tests/test_tx_graph_conflicts.rs
Labels: bug

#1121 feat: add dependabot
  .github/dependabot.yml
Labels: ci

#1178 `LocalChain` with hardwired genesis block
  crates/bdk/Cargo.toml
  crates/bdk/src/wallet/coin_selection.rs
  crates/bdk/src/wallet/mod.rs
  crates/bdk/tests/wallet.rs
  crates/bitcoind_rpc/src/lib.rs
  crates/bitcoind_rpc/tests/test_emitter.rs
  crates/chain/src/chain_oracle.rs
  crates/chain/src/local_chain.rs
  crates/chain/src/persist.rs
  crates/chain/tests/common/mod.rs
  crates/chain/tests/test_indexed_tx_graph.rs
  crates/chain/tests/test_keychain_txout_index.rs
  crates/chain/tests/test_local_chain.rs
  crates/chain/tests/test_tx_graph.rs
  crates/chain/tests/test_tx_graph_conflicts.rs
  crates/electrum/src/electrum_ext.rs
  crates/esplora/src/async_ext.rs
  crates/esplora/src/blocking_ext.rs
  crates/file_store/src/store.rs
  crates/file_store/tests/test_file_store.rs
  example-crates/example_bitcoind_rpc_polling/src/main.rs
  example-crates/example_cli/src/lib.rs
  example-crates/example_electrum/src/main.rs
  example-crates/example_esplora/src/main.rs
  example-crates/wallet_electrum/src/main.rs
  example-crates/wallet_esplora_async/src/main.rs
  example-crates/wallet_esplora_blocking/src/main.rs
Labels: module-blockchain, module-wallet

#1028 Add CreateTxError and use as error type for TxBuilder::finish()
  .github/workflows/cont_integration.yml
  README.md
  crates/bdk/Cargo.toml
  crates/bdk/examples/mnemonic_to_descriptors.rs
  crates/bdk/src/descriptor/error.rs
  crates/bdk/src/descriptor/policy.rs
  crates/bdk/src/error.rs
  crates/bdk/src/keys/mod.rs
  crates/bdk/src/lib.rs
  crates/bdk/src/wallet/coin_selection.rs
  crates/bdk/src/wallet/error.rs
  crates/bdk/src/wallet/mod.rs
  crates/bdk/src/wallet/signer.rs
  crates/bdk/src/wallet/tx_builder.rs
  crates/bdk/tests/wallet.rs
  crates/chain/src/tx_graph.rs
  example-crates/wallet_electrum/Cargo.toml
  example-crates/wallet_electrum/src/main.rs
  example-crates/wallet_esplora_async/Cargo.toml
  example-crates/wallet_esplora_async/src/main.rs
  example-crates/wallet_esplora_blocking/Cargo.toml
  example-crates/wallet_esplora_blocking/src/main.rs
Labels: module-wallet

#1190 Add `Wallet::list_output` method
  crates/bdk/src/types.rs
  crates/bdk/src/wallet/coin_selection.rs
  crates/bdk/src/wallet/mod.rs
  crates/bdk/src/wallet/tx_builder.rs
  crates/bdk/tests/common.rs
  crates/bdk/tests/wallet.rs
Labels: enhancement, module-wallet
