Repository bitcoindevkit/bdk, pull requests merged in 2023-05, with the labels that each got.

#960 Reenable code coverage upload to Coveralls
  .github/workflows/code_coverage.yml
Labels: ci

#927 Custom spk iterator
  crates/chain/src/keychain/txout_index.rs
  crates/chain/src/lib.rs
  crates/chain/src/spk_iter.rs
Labels: BDK 1.0.0

#963 Various tweaks to redesigned structures
  crates/chain/src/chain_data.rs
  crates/chain/src/chain_oracle.rs
  crates/chain/src/indexed_tx_graph.rs
  crates/chain/src/keychain/txout_index.rs
  crates/chain/src/local_chain.rs
  crates/chain/src/spk_txout_index.rs
  crates/chain/src/tx_graph.rs
  crates/chain/tests/test_indexed_tx_graph.rs
  crates/chain/tests/test_local_chain.rs
  crates/chain/tests/test_tx_graph.rs
Labels: BDK 1.0.0

#981 Fixed typos in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#957 Documentation regarding absolute_fee and fee_rate updated
  crates/bdk/src/wallet/tx_builder.rs
Labels: documentation
