Repository bitcoindevkit/bdk, pull requests merged in 2023-10, with the labels that each got.

#1064 Better tests for transaction conflict handling
  crates/chain/src/tx_graph.rs
  crates/chain/tests/common/mod.rs
  crates/chain/tests/common/tx_template.rs
  crates/chain/tests/test_tx_graph.rs
  crates/chain/tests/test_tx_graph_conflicts.rs
Labels: tests

#1152 fix(wallet_esplora): missing_heights uses the graph update
  example-crates/wallet_esplora_async/src/main.rs
  example-crates/wallet_esplora_blocking/src/main.rs
Labels: bug

#1169 Bump bdk version to 1.0.0-alpha.2
  crates/bdk/Cargo.toml
  crates/bitcoind_rpc/Cargo.toml
  crates/chain/Cargo.toml
  crates/electrum/Cargo.toml
  crates/esplora/Cargo.toml
  crates/file_store/Cargo.toml
Labels: release

#1174 chore: add meta data to bitcoind_rpc crate
  crates/bitcoind_rpc/Cargo.toml
  crates/bitcoind_rpc/README.md
Labels: release
