Repository bitcoindevkit/bdk, pull requests merged in 2023-08, with the labels that each got.

#1039 docs: add required style for commit messages
  CONTRIBUTING.md
Labels: documentation, discussion

#1057 release: bump version to 0.28.1
  CHANGELOG.md
  Cargo.toml
Labels: release

#1077 fix: msrv issues
  .github/workflows/code_coverage.yml
  .github/workflows/cont_integration.yml
Labels: ci

#1087 ci: fix msrv dependency versions for reqest and h2
  .github/workflows/cont_integration.yml
  README.md
Labels: ci

#1082 docs: add License and Contributing sections to repo top-level README
  LICENSE
  LICENSE-APACHE
  LICENSE-MIT
  README.md
  crates/bdk/README.md
Labels: documentation

#1091 ci: Pin rustls-webpki to 0.100.1
  .github/workflows/cont_integration.yml
  README.md
Labels: ci

#1090 fix(electrum): Don't ignore multiple coinbase txs
  .github/workflows/cont_integration.yml
  README.md
  src/blockchain/script_sync.rs
  src/testutils/blockchain_tests.rs
Labels: bug, ci

#1085 docs: Update README.md
  Cargo.toml
  README.md
  example-crates/wallet_esplora_blocking/Cargo.toml
  example-crates/wallet_esplora_blocking/src/main.rs
Labels: documentation

#1048 Remove TransactionDetails from Wallet API
  .github/workflows/cont_integration.yml
  README.md
  crates/bdk/src/keys/mod.rs
  crates/bdk/src/types.rs
  crates/bdk/src/wallet/coin_selection.rs
  crates/bdk/src/wallet/mod.rs
  crates/bdk/src/wallet/tx_builder.rs
  crates/bdk/tests/common.rs
  crates/bdk/tests/psbt.rs
  crates/bdk/tests/wallet.rs
  crates/chain/src/spk_txout_index.rs
  crates/chain/src/tx_graph.rs
  crates/chain/tests/test_tx_graph.rs
  example-crates/wallet_electrum/src/main.rs
  example-crates/wallet_esplora_async/src/main.rs
  example-crates/wallet_esplora_blocking/src/main.rs
Labels: tests, module-wallet
