Repository bitcoindevkit/bdk, pull requests merged in 2024-10, with the labels that each got.

#1625 feat(chain,core)!: move `Merge` to `bdk_core`
  crates/chain/src/tx_data_traits.rs
  crates/core/src/lib.rs
  crates/core/src/merge.rs
  crates/file_store/Cargo.toml
  crates/file_store/src/store.rs
Labels: dependencies, chore

#1636 ci: fix build-test job with --no-default-features, add miniscript/no-std
  .github/workflows/cont_integration.yml
Labels: ci

#1620 feat(bdk_electrum): add `use-openssl` as a feature
  crates/electrum/Cargo.toml
Labels: new feature, module-blockchain

#1639 Bump bdk_wallet version to 1.0.0-beta.5
  crates/bitcoind_rpc/Cargo.toml
  crates/chain/Cargo.toml
  crates/core/Cargo.toml
  crates/electrum/Cargo.toml
  crates/esplora/Cargo.toml
  crates/file_store/Cargo.toml
  crates/testenv/Cargo.toml
  crates/wallet/Cargo.toml
Labels: release

#1612 Refactor: Move transaction testing utilities from `crates/chain/tests/common` to `testenv` crate
  crates/chain/Cargo.toml
  crates/chain/tests/common/mod.rs
  crates/chain/tests/common/tx_template.rs
  crates/chain/tests/test_indexed_tx_graph.rs
  crates/chain/tests/test_keychain_txout_index.rs
  crates/chain/tests/test_local_chain.rs
  crates/chain/tests/test_tx_graph.rs
  crates/chain/tests/test_tx_graph_conflicts.rs
  crates/core/Cargo.toml
  crates/core/tests/common.rs
  crates/core/tests/test_checkpoint.rs
  crates/testenv/src/lib.rs
  crates/testenv/src/utils.rs
Labels: tests

#1646 ci: update audit.yml workflow to use actions-rust-lang/audit
  .github/workflows/audit.yml
Labels: ci

#1159 (maintenance) doc(bdk): Clarify the absolute_fee docs
  src/wallet/tx_builder.rs
Labels: documentation, module-wallet

#1643 feat(chain,wallet)!: rm `ConfirmationTime`
  crates/chain/src/chain_data.rs
  crates/wallet/src/types.rs
  crates/wallet/src/wallet/coin_selection.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/src/wallet/tx_builder.rs
  crates/wallet/tests/common.rs
  crates/wallet/tests/wallet.rs
Labels: api, chore

#1662 fix(wallet): fix building change signers in `load_with_params`
  crates/wallet/src/wallet/mod.rs
  crates/wallet/tests/wallet.rs
Labels: bug

#1652 refactor(chain)!: remove `inner` method from KeychainTxOutIndex
  crates/chain/src/indexer/keychain_txout.rs
  crates/chain/tests/test_keychain_txout_index.rs
Labels: module-blockchain, api
