Repository bitcoindevkit/bdk, pull requests merged in 2024-04, with the labels that each got.

#1345 fix: remove deprecated max_satisfaction_weight
  crates/bdk/src/wallet/coin_selection.rs
  crates/bdk/src/wallet/mod.rs
  crates/bdk/src/wallet/tx_builder.rs
  crates/bdk/tests/wallet.rs
Labels: module-wallet, api

#1369 feat(chain): add `get` and `range` methods to `CheckPoint`
  crates/bdk/src/wallet/mod.rs
  crates/bitcoind_rpc/tests/test_emitter.rs
  crates/chain/src/local_chain.rs
  crates/chain/src/tx_graph.rs
  crates/chain/tests/test_indexed_tx_graph.rs
  crates/chain/tests/test_local_chain.rs
  crates/esplora/tests/blocking_ext.rs
Labels: module-blockchain, api

#1385 Fix last seen unconfirmed
  crates/chain/src/tx_graph.rs
  crates/chain/tests/test_tx_graph.rs
  crates/electrum/src/electrum_ext.rs
  crates/electrum/tests/test_electrum.rs
  example-crates/example_electrum/src/main.rs
  example-crates/example_esplora/src/main.rs
  example-crates/wallet_electrum/src/main.rs
  example-crates/wallet_esplora_async/src/main.rs
  example-crates/wallet_esplora_blocking/src/main.rs
Labels: module-blockchain, api

#1177 Upgrade bitcoin/miniscript dependencies
  crates/bdk/Cargo.toml
  crates/bdk/src/descriptor/dsl.rs
  crates/bdk/src/descriptor/error.rs
  crates/bdk/src/descriptor/mod.rs
  crates/bdk/src/descriptor/policy.rs
  crates/bdk/src/descriptor/template.rs
  crates/bdk/src/keys/bip39.rs
  crates/bdk/src/keys/mod.rs
  crates/bdk/src/psbt/mod.rs
  crates/bdk/src/wallet/coin_selection.rs
  crates/bdk/src/wallet/export.rs
  crates/bdk/src/wallet/hardwaresigner.rs
  crates/bdk/src/wallet/mod.rs
  crates/bdk/src/wallet/signer.rs
  crates/bdk/src/wallet/tx_builder.rs
  crates/bdk/src/wallet/utils.rs
  crates/bdk/tests/common.rs
  crates/bdk/tests/psbt.rs
  crates/bdk/tests/wallet.rs
  crates/bitcoind_rpc/Cargo.toml
  crates/bitcoind_rpc/tests/test_emitter.rs
  crates/chain/Cargo.toml
  crates/chain/src/spk_txout_index.rs
  crates/chain/src/tx_graph.rs
  crates/chain/tests/common/mod.rs
  crates/chain/tests/common/tx_template.rs
  crates/chain/tests/test_indexed_tx_graph.rs
  crates/chain/tests/test_keychain_txout_index.rs
  crates/chain/tests/test_spk_txout_index.rs
  crates/chain/tests/test_tx_graph.rs
  crates/electrum/Cargo.toml
  crates/electrum/tests/test_electrum.rs
  crates/esplora/Cargo.toml
  crates/esplora/src/async_ext.rs
  crates/esplora/src/blocking_ext.rs
  crates/esplora/tests/blocking_ext.rs
  crates/hwi/Cargo.toml
  crates/hwi/src/signer.rs
  crates/testenv/Cargo.toml
  crates/testenv/src/lib.rs
  example-crates/example_cli/src/lib.rs
  example-crates/example_esplora/src/main.rs
  example-crates/wallet_electrum/src/main.rs
  example-crates/wallet_esplora_async/src/main.rs
  example-crates/wallet_esplora_blocking/src/main.rs
  nursery/coin_select/src/coin_selector.rs
  nursery/coin_select/src/lib.rs
  nursery/tmp_plan/src/lib.rs
  nursery/tmp_plan/src/requirements.rs
Labels: module-wallet, dependencies, api

#1404 Bump bdk version to 1.0.0-alpha.9
  crates/bdk/Cargo.toml
  crates/bitcoind_rpc/Cargo.toml
  crates/chain/Cargo.toml
  crates/electrum/Cargo.toml
  crates/esplora/Cargo.toml
  crates/file_store/Cargo.toml
  crates/testenv/Cargo.toml
Labels: release

#1324 [chain] Make KeychainTxOutIndex more range based
  crates/bdk/src/wallet/mod.rs
  crates/chain/src/keychain/txout_index.rs
  crates/chain/src/spk_txout_index.rs
  crates/chain/tests/test_spk_txout_index.rs
  example-crates/example_electrum/src/main.rs
  example-crates/example_esplora/src/main.rs
Labels: module-blockchain, api

#1387 fix(wallet): remove the generic from wallet
  crates/bdk/Cargo.toml
  crates/bdk/src/wallet/error.rs
  crates/bdk/src/wallet/export.rs
  crates/bdk/src/wallet/mod.rs
  crates/bdk/src/wallet/tx_builder.rs
  crates/chain/Cargo.toml
  crates/chain/src/persist.rs
  crates/file_store/Cargo.toml
  crates/file_store/src/store.rs
  example-crates/example_cli/src/lib.rs
Labels: module-wallet, api

#1408 Fix: enable blocking-https-rustls feature on esplora client
  crates/esplora/Cargo.toml
Labels: module-blockchain
