Repository bitcoindevkit/bdk, pull requests merged in 2024-07, with the labels that each got.

#1416 [chain] Change tx_last_seen to `Option<u64>`
  crates/bitcoind_rpc/tests/test_emitter.rs
  crates/chain/src/tx_graph.rs
  crates/chain/tests/common/tx_template.rs
  crates/chain/tests/test_indexed_tx_graph.rs
  crates/chain/tests/test_tx_graph.rs
  crates/chain/tests/test_tx_graph_conflicts.rs
  crates/electrum/tests/test_electrum.rs
  crates/wallet/src/wallet/export.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/tests/common.rs
  crates/wallet/tests/wallet.rs
  example-crates/example_electrum/src/main.rs
  example-crates/example_esplora/src/main.rs
Labels: module-blockchain, api

#1493 [chain] Create module `indexer`
  crates/bitcoind_rpc/tests/test_emitter.rs
  crates/chain/src/balance.rs
  crates/chain/src/changeset.rs
  crates/chain/src/indexed_tx_graph.rs
  crates/chain/src/indexer.rs
  crates/chain/src/indexer/keychain_txout.rs
  crates/chain/src/indexer/spk_txout.rs
  crates/chain/src/lib.rs
  crates/chain/src/spk_client.rs
  crates/chain/src/spk_iter.rs
  crates/chain/src/tx_graph.rs
  crates/chain/tests/test_indexed_tx_graph.rs
  crates/chain/tests/test_keychain_txout_index.rs
  crates/chain/tests/test_spk_txout_index.rs
  crates/chain/tests/test_tx_graph_conflicts.rs
  crates/electrum/tests/test_electrum.rs
  crates/esplora/src/async_ext.rs
  crates/esplora/src/blocking_ext.rs
  crates/sqlite/src/store.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/tests/common.rs
  example-crates/example_bitcoind_rpc_polling/src/main.rs
  example-crates/example_cli/src/lib.rs
  example-crates/example_electrum/src/main.rs
  example-crates/example_esplora/src/main.rs
Labels: api

#1502 chore(chain)!: Rename `Append` to `Merge`
  crates/bitcoind_rpc/tests/test_emitter.rs
  crates/chain/src/changeset.rs
  crates/chain/src/indexed_tx_graph.rs
  crates/chain/src/indexer/keychain_txout.rs
  crates/chain/src/tx_data_traits.rs
  crates/chain/src/tx_graph.rs
  crates/chain/tests/test_indexed_tx_graph.rs
  crates/chain/tests/test_keychain_txout_index.rs
  crates/chain/tests/test_tx_graph.rs
  crates/file_store/src/store.rs
  crates/sqlite/src/store.rs
  crates/wallet/src/wallet/mod.rs
  example-crates/example_bitcoind_rpc_polling/src/main.rs
  example-crates/example_cli/src/lib.rs
  example-crates/example_electrum/src/main.rs
  example-crates/example_esplora/src/main.rs
Labels: api

#1503 feat(wallet): simplify `public_descriptor` fn and remove `get_descriptor_for_keych…
  crates/wallet/src/wallet/export.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/src/wallet/tx_builder.rs
  crates/wallet/tests/wallet.rs
Labels: module-wallet, api

#1489 feat(electrum)!: Update `bdk_electrum` to use merkle proofs
  crates/chain/src/chain_data.rs
  crates/chain/src/spk_client.rs
  crates/chain/src/tx_data_traits.rs
  crates/chain/tests/test_indexed_tx_graph.rs
  crates/chain/tests/test_tx_graph.rs
  crates/electrum/src/bdk_electrum_client.rs
  crates/electrum/tests/test_electrum.rs
  crates/esplora/src/async_ext.rs
  crates/esplora/src/blocking_ext.rs
  crates/esplora/src/lib.rs
  crates/sqlite/src/store.rs
  crates/wallet/src/wallet/export.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/tests/common.rs
  example-crates/example_bitcoind_rpc_polling/src/main.rs
  example-crates/example_electrum/src/main.rs
  example-crates/example_esplora/src/main.rs
  example-crates/wallet_electrum/src/main.rs
Labels: api

#1514 refactor(wallet)!: rework persistence, changeset, and construction
  Cargo.toml
  crates/bitcoind_rpc/tests/test_emitter.rs
  crates/chain/Cargo.toml
  crates/chain/src/changeset.rs
  crates/chain/src/indexed_tx_graph.rs
  crates/chain/src/indexer/keychain_txout.rs
  crates/chain/src/indexer/spk_txout.rs
  crates/chain/src/lib.rs
  crates/chain/src/local_chain.rs
  crates/chain/src/persist.rs
  crates/chain/src/rusqlite_impl.rs
  crates/chain/tests/common/tx_template.rs
  crates/chain/tests/test_indexed_tx_graph.rs
  crates/chain/tests/test_keychain_txout_index.rs
  crates/chain/tests/test_spk_txout_index.rs
  crates/electrum/tests/test_electrum.rs
  crates/hwi/src/lib.rs
  crates/hwi/src/signer.rs
  crates/sqlite/Cargo.toml
  crates/sqlite/README.md
  crates/sqlite/schema/schema_0.sql
  crates/sqlite/src/lib.rs
  crates/sqlite/src/schema.rs
  crates/sqlite/src/store.rs
  crates/wallet/Cargo.toml
  crates/wallet/README.md
  crates/wallet/examples/compiler.rs
  crates/wallet/examples/policy.rs
  crates/wallet/src/descriptor/error.rs
  crates/wallet/src/descriptor/mod.rs
  crates/wallet/src/descriptor/policy.rs
  crates/wallet/src/descriptor/template.rs
  crates/wallet/src/keys/mod.rs
  crates/wallet/src/lib.rs
  crates/wallet/src/wallet/changeset.rs
  crates/wallet/src/wallet/coin_selection.rs
  crates/wallet/src/wallet/export.rs
  crates/wallet/src/wallet/hardwaresigner.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/src/wallet/params.rs
  crates/wallet/src/wallet/persisted.rs
  crates/wallet/src/wallet/signer.rs
  crates/wallet/src/wallet/tx_builder.rs
  crates/wallet/tests/common.rs
  crates/wallet/tests/wallet.rs
  example-crates/example_bitcoind_rpc_polling/src/main.rs
  example-crates/example_cli/src/lib.rs
  example-crates/example_electrum/src/main.rs
  example-crates/example_esplora/src/main.rs
  example-crates/wallet_electrum/Cargo.toml
  example-crates/wallet_electrum/src/main.rs
  example-crates/wallet_esplora_async/Cargo.toml
  example-crates/wallet_esplora_async/src/main.rs
  example-crates/wallet_esplora_blocking/Cargo.toml
  example-crates/wallet_esplora_blocking/src/main.rs
  example-crates/wallet_rpc/Cargo.toml
  example-crates/wallet_rpc/src/main.rs
Labels: module-wallet, api

#1506 Standardize API ownership in `KeychainTxOutIndex`
  crates/chain/src/indexer/keychain_txout.rs
  crates/chain/src/indexer/spk_txout.rs
  crates/chain/src/tx_graph.rs
  crates/chain/tests/common/tx_template.rs
  crates/chain/tests/test_indexed_tx_graph.rs
  crates/chain/tests/test_keychain_txout_index.rs
  crates/chain/tests/test_tx_graph_conflicts.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/tests/wallet.rs
  example-crates/example_cli/src/lib.rs
  example-crates/example_electrum/src/main.rs
Labels: module-blockchain, api

#1522 Bump bdk version to 1.0.0-beta.1
  crates/bitcoind_rpc/Cargo.toml
  crates/chain/Cargo.toml
  crates/electrum/Cargo.toml
  crates/esplora/Cargo.toml
  crates/file_store/Cargo.toml
  crates/hwi/Cargo.toml
  crates/testenv/Cargo.toml
  crates/wallet/Cargo.toml
Labels: release

#1524 ci: pin tokio to 1.38.1 to support MSRV 1.63
  .github/workflows/cont_integration.yml
  README.md
Labels: ci
