Repository bitcoindevkit/bdk, pull requests merged in 2024-06, with the labels that each got.

#1426 feat: add further `bitcoin::Amount` usage on public APIs
  crates/chain/src/tx_graph.rs
  crates/chain/tests/test_tx_graph.rs
  crates/electrum/tests/test_electrum.rs
  crates/esplora/tests/async_ext.rs
  crates/esplora/tests/blocking_ext.rs
  crates/wallet/src/psbt/mod.rs
  crates/wallet/src/wallet/error.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/src/wallet/tx_builder.rs
  crates/wallet/tests/wallet.rs
Labels: module-blockchain, module-wallet, api

#1455 refactor(wallet): rename get_balance() to balance()
  crates/wallet/README.md
  crates/wallet/src/wallet/mod.rs
  crates/wallet/tests/psbt.rs
  crates/wallet/tests/wallet.rs
  example-crates/wallet_electrum/src/main.rs
  example-crates/wallet_esplora_async/src/main.rs
  example-crates/wallet_esplora_blocking/src/main.rs
  example-crates/wallet_rpc/src/main.rs
Labels: module-wallet, api

#1453 refactor(electrum) put the tx cache in electrum
  crates/chain/src/indexed_tx_graph.rs
  crates/chain/src/spk_client.rs
  crates/electrum/src/bdk_electrum_client.rs
  crates/electrum/src/lib.rs
  crates/electrum/tests/test_electrum.rs
  crates/wallet/src/wallet/mod.rs
  example-crates/example_electrum/src/main.rs
  example-crates/wallet_electrum/src/main.rs
Labels: api

#1390 Make Wallet require a change descriptor
  crates/hwi/src/lib.rs
  crates/wallet/README.md
  crates/wallet/examples/compiler.rs
  crates/wallet/src/descriptor/error.rs
  crates/wallet/src/descriptor/template.rs
  crates/wallet/src/wallet/error.rs
  crates/wallet/src/wallet/export.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/src/wallet/signer.rs
  crates/wallet/tests/common.rs
  crates/wallet/tests/psbt.rs
  crates/wallet/tests/wallet.rs
  example-crates/wallet_electrum/src/main.rs
  example-crates/wallet_esplora_async/src/main.rs
  example-crates/wallet_esplora_blocking/src/main.rs
  example-crates/wallet_rpc/src/main.rs
Labels: module-wallet, api

#1441 Remove duplicated InsufficientFunds error member
  crates/wallet/src/wallet/error.rs
  crates/wallet/src/wallet/mod.rs
Labels: module-wallet

#1470 ci: pin url dependency version to build with rust 1.63
  .github/workflows/cont_integration.yml
  README.md
Labels: ci

#1448 bump(deps): upgrade rust `bitcoin` to `0.32.0`, `miniscript` to `0.12.0` and others
  .github/workflows/cont_integration.yml
  crates/bitcoind_rpc/Cargo.toml
  crates/bitcoind_rpc/tests/test_emitter.rs
  crates/chain/Cargo.toml
  crates/chain/src/descriptor_ext.rs
  crates/chain/src/indexed_tx_graph.rs
  crates/chain/src/keychain/txout_index.rs
  crates/chain/src/spk_txout_index.rs
  crates/chain/src/tx_data_traits.rs
  crates/chain/src/tx_graph.rs
  crates/chain/tests/common/tx_template.rs
  crates/chain/tests/test_indexed_tx_graph.rs
  crates/chain/tests/test_spk_txout_index.rs
  crates/chain/tests/test_tx_graph.rs
  crates/electrum/Cargo.toml
  crates/electrum/src/bdk_electrum_client.rs
  crates/esplora/Cargo.toml
  crates/hwi/Cargo.toml
  crates/sqlite/src/store.rs
  crates/testenv/Cargo.toml
  crates/wallet/Cargo.toml
  crates/wallet/src/descriptor/dsl.rs
  crates/wallet/src/descriptor/error.rs
  crates/wallet/src/descriptor/mod.rs
  crates/wallet/src/descriptor/policy.rs
  crates/wallet/src/descriptor/template.rs
  crates/wallet/src/keys/mod.rs
  crates/wallet/src/wallet/coin_selection.rs
  crates/wallet/src/wallet/export.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/src/wallet/signer.rs
  crates/wallet/src/wallet/tx_builder.rs
  crates/wallet/src/wallet/utils.rs
  crates/wallet/tests/common.rs
  crates/wallet/tests/wallet.rs
  example-crates/example_cli/src/lib.rs
  example-crates/wallet_electrum/src/main.rs
  example-crates/wallet_esplora_async/src/main.rs
  example-crates/wallet_esplora_blocking/src/main.rs
  nursery/tmp_plan/src/plan_impls.rs
  nursery/tmp_plan/src/requirements.rs
Labels: api

#1463 No descriptor ids in spk txout index
  clippy.toml
  crates/chain/src/keychain.rs
  crates/chain/src/keychain/txout_index.rs
  crates/chain/src/lib.rs
  crates/chain/src/spk_client.rs
  crates/chain/src/spk_iter.rs
  crates/chain/src/spk_txout_index.rs
  crates/chain/tests/test_indexed_tx_graph.rs
  crates/chain/tests/test_keychain_txout_index.rs
  crates/esplora/src/async_ext.rs
  crates/esplora/src/blocking_ext.rs
  crates/wallet/src/descriptor/error.rs
  crates/wallet/src/wallet/mod.rs
  example-crates/example_bitcoind_rpc_polling/src/main.rs
  example-crates/example_cli/src/lib.rs
  example-crates/example_electrum/src/main.rs
  example-crates/example_esplora/src/main.rs
Labels: module-blockchain

#1454 Refactor wallet and persist mod, remove bdk_persist crate
  Cargo.toml
  crates/chain/Cargo.toml
  crates/chain/src/keychain/txout_index.rs
  crates/chain/src/lib.rs
  crates/chain/src/persist.rs
  crates/chain/src/spk_client.rs
  crates/file_store/Cargo.toml
  crates/file_store/README.md
  crates/file_store/src/store.rs
  crates/hwi/src/lib.rs
  crates/persist/Cargo.toml
  crates/persist/README.md
  crates/persist/src/changeset.rs
  crates/persist/src/lib.rs
  crates/persist/src/persist.rs
  crates/sqlite/Cargo.toml
  crates/sqlite/README.md
  crates/sqlite/src/store.rs
  crates/wallet/Cargo.toml
  crates/wallet/README.md
  crates/wallet/examples/compiler.rs
  crates/wallet/src/descriptor/template.rs
  crates/wallet/src/wallet/coin_selection.rs
  crates/wallet/src/wallet/error.rs
  crates/wallet/src/wallet/export.rs
  crates/wallet/src/wallet/hardwaresigner.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/src/wallet/signer.rs
  crates/wallet/src/wallet/tx_builder.rs
  crates/wallet/tests/common.rs
  crates/wallet/tests/wallet.rs
  example-crates/example_bitcoind_rpc_polling/src/main.rs
  example-crates/example_cli/Cargo.toml
  example-crates/example_cli/src/lib.rs
  example-crates/example_electrum/src/main.rs
  example-crates/example_esplora/src/main.rs
  example-crates/wallet_electrum/src/main.rs
  example-crates/wallet_esplora_async/src/main.rs
  example-crates/wallet_esplora_blocking/src/main.rs
  example-crates/wallet_rpc/src/main.rs
Labels: module-blockchain, module-database, module-wallet, api

#1473 Remove `persist` submodule
  crates/chain/Cargo.toml
  crates/chain/src/changeset.rs
  crates/chain/src/lib.rs
  crates/chain/src/persist.rs
  crates/chain/src/tx_data_traits.rs
  crates/file_store/Cargo.toml
  crates/file_store/README.md
  crates/file_store/src/store.rs
  crates/sqlite/Cargo.toml
  crates/sqlite/README.md
  crates/sqlite/src/store.rs
  crates/wallet/Cargo.toml
  crates/wallet/README.md
  crates/wallet/src/wallet/mod.rs
  crates/wallet/tests/wallet.rs
  example-crates/example_bitcoind_rpc_polling/src/main.rs
  example-crates/example_cli/src/lib.rs
  example-crates/example_electrum/src/main.rs
  example-crates/example_esplora/src/main.rs
  example-crates/wallet_electrum/src/main.rs
  example-crates/wallet_esplora_async/src/main.rs
  example-crates/wallet_esplora_blocking/src/main.rs
  example-crates/wallet_rpc/src/main.rs
Labels: api

#1472 Bump bdk version to 1.0.0-alpha.13
  crates/bitcoind_rpc/Cargo.toml
  crates/chain/Cargo.toml
  crates/electrum/Cargo.toml
  crates/esplora/Cargo.toml
  crates/file_store/Cargo.toml
  crates/hwi/Cargo.toml
  crates/sqlite/Cargo.toml
  crates/testenv/Cargo.toml
  crates/wallet/Cargo.toml
Labels: release

#1395 Remove `rand` dependency from `bdk`
  .github/workflows/cont_integration.yml
  crates/esplora/src/blocking_ext.rs
  crates/wallet/Cargo.toml
  crates/wallet/README.md
  crates/wallet/src/keys/mod.rs
  crates/wallet/src/wallet/coin_selection.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/src/wallet/signer.rs
  crates/wallet/src/wallet/tx_builder.rs
  crates/wallet/src/wallet/utils.rs
  crates/wallet/tests/wallet.rs
Labels: module-wallet, module-keys, api

#1424 Remove trait ComputeSighash
  crates/wallet/src/wallet/signer.rs
Labels: module-wallet, api

#1468 feat: use `Weight` type instead of `usize`
  crates/wallet/src/types.rs
  crates/wallet/src/wallet/coin_selection.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/src/wallet/tx_builder.rs
  crates/wallet/tests/wallet.rs
Labels: api

#1486 refactor(chain): calculate DescriptorId as the sha256 hash of the spk at index 0
  crates/chain/src/descriptor_ext.rs
  crates/chain/src/keychain/txout_index.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/tests/wallet.rs
Labels: bug, module-blockchain
