Repository bitcoindevkit/bdk, pull requests merged in 2024-01, with the labels that each got.

#1258 fix(typos): existant -> existent
  crates/bdk/src/wallet/mod.rs
  crates/bdk/tests/wallet.rs
  crates/file_store/src/store.rs
Labels: documentation

#1255 Bump bdk version to 1.0.0-alpha.3
  crates/bdk/Cargo.toml
  crates/bitcoind_rpc/Cargo.toml
  crates/chain/Cargo.toml
  crates/electrum/Cargo.toml
  crates/esplora/Cargo.toml
  crates/file_store/Cargo.toml
Labels: release

#1274 Avoid using `BTreeMap::append`
  crates/chain/src/keychain.rs
  crates/chain/src/tx_data_traits.rs
  crates/chain/src/tx_graph.rs
Labels: bug

#1276 Add `LocalChain::disconnect_from` method
  crates/chain/src/local_chain.rs
  crates/chain/tests/test_local_chain.rs
Labels: enhancement

#1269 Revamp `KeychainTxOutIndex` API to be safer
  crates/bdk/src/wallet/mod.rs
  crates/chain/src/keychain/txout_index.rs
  crates/chain/src/spk_iter.rs
  crates/chain/src/spk_txout_index.rs
  crates/chain/tests/test_keychain_txout_index.rs
  crates/electrum/src/electrum_ext.rs
  example-crates/example_cli/src/lib.rs
  example-crates/example_electrum/src/main.rs
  example-crates/example_esplora/src/main.rs
  example-crates/wallet_electrum/src/main.rs
  example-crates/wallet_esplora_async/src/main.rs
  example-crates/wallet_esplora_blocking/src/main.rs
Labels: bug, api

#1282 Bump version to 1.0.0-alpha.4
  crates/bdk/Cargo.toml
  crates/bitcoind_rpc/Cargo.toml
  crates/chain/Cargo.toml
  crates/electrum/Cargo.toml
  crates/esplora/Cargo.toml
  crates/file_store/Cargo.toml
Labels: release

#1253 Remove deprecated checksum routines
  crates/bdk/src/descriptor/checksum.rs
Labels: api

#1294 Expose `SpkIterator::new_with_range`
  crates/chain/src/spk_iter.rs
Labels: enhancement

#1279 Filter duplicate coins before coin selection
  crates/bdk/src/wallet/coin_selection.rs
  crates/bdk/src/wallet/mod.rs
Labels: bug

#1306 Implement `ElectrumExt` for all that implements `ElectrumApi`
  crates/electrum/src/electrum_ext.rs
Labels: enhancement

#1307 Bump version to 1.0.0-alpha.5
  crates/bdk/Cargo.toml
  crates/bitcoind_rpc/Cargo.toml
  crates/chain/Cargo.toml
  crates/electrum/Cargo.toml
  crates/esplora/Cargo.toml
  crates/file_store/Cargo.toml
Labels: release
