Repository bitcoindevkit/bdk, pull requests merged in 2024-05, with the labels that each got.

#1413 Introduce universal sync/full-scan structures for spk-based syncing
  crates/bdk/src/wallet/mod.rs
  crates/chain/src/lib.rs
  crates/chain/src/spk_client.rs
  crates/esplora/src/async_ext.rs
  crates/esplora/src/blocking_ext.rs
  crates/esplora/src/lib.rs
  crates/esplora/tests/async_ext.rs
  crates/esplora/tests/blocking_ext.rs
  example-crates/example_esplora/src/main.rs
  example-crates/wallet_esplora_async/src/main.rs
  example-crates/wallet_esplora_blocking/src/main.rs
Labels: api

#1417 test(wallet): add thread safety test
  crates/bdk/tests/wallet.rs
Labels: tests

#1427 docs(esplora): fixed `full_scan` and `sync` documentation
  crates/esplora/src/async_ext.rs
  crates/esplora/src/blocking_ext.rs
Labels: documentation

#1411 feat: update `keychain::Balance` to use `bitcoin::Amount`
  crates/bdk/src/wallet/coin_selection.rs
  crates/bdk/src/wallet/mod.rs
  crates/bdk/src/wallet/tx_builder.rs
  crates/bdk/tests/psbt.rs
  crates/bdk/tests/wallet.rs
  crates/bitcoind_rpc/tests/test_emitter.rs
  crates/chain/src/keychain.rs
  crates/chain/src/keychain/txout_index.rs
  crates/chain/src/spk_txout_index.rs
  crates/chain/src/tx_graph.rs
  crates/chain/tests/test_indexed_tx_graph.rs
  crates/chain/tests/test_spk_txout_index.rs
  crates/chain/tests/test_tx_graph_conflicts.rs
  crates/electrum/tests/test_electrum.rs
  example-crates/example_cli/src/lib.rs
  example-crates/wallet_electrum/src/main.rs
  example-crates/wallet_esplora_async/src/main.rs
  example-crates/wallet_esplora_blocking/src/main.rs
Labels: module-wallet, api

#1423 fix(persist): add default feature to enable bdk_chain/std
  crates/persist/Cargo.toml
Labels: bug

#1430 ci: Pin clippy to rust 1.78.0
  .github/workflows/cont_integration.yml
Labels: ci

#1203 Include the descriptor in `keychain::Changeset`
  crates/bdk/src/wallet/mod.rs
  crates/bdk/tests/wallet.rs
  crates/chain/Cargo.toml
  crates/chain/src/descriptor_ext.rs
  crates/chain/src/indexed_tx_graph.rs
  crates/chain/src/keychain.rs
  crates/chain/src/keychain/txout_index.rs
  crates/chain/src/lib.rs
  crates/chain/src/spk_iter.rs
  crates/chain/tests/common/mod.rs
  crates/chain/tests/common/tx_template.rs
  crates/chain/tests/test_indexed_tx_graph.rs
  crates/chain/tests/test_keychain_txout_index.rs
  crates/chain/tests/test_local_chain.rs
  crates/chain/tests/test_tx_graph.rs
  crates/chain/tests/test_tx_graph_conflicts.rs
  example-crates/example_bitcoind_rpc_polling/src/main.rs
  example-crates/example_cli/src/lib.rs
  example-crates/example_electrum/src/main.rs
  example-crates/example_esplora/src/main.rs
Labels: module-blockchain, module-database, api

#1403 Update `bdk_electrum` crate to use sync/full-scan structs
  crates/bdk/src/wallet/mod.rs
  crates/chain/src/spk_client.rs
  crates/chain/src/tx_graph.rs
  crates/electrum/Cargo.toml
  crates/electrum/src/electrum_ext.rs
  crates/electrum/src/lib.rs
  crates/electrum/tests/test_electrum.rs
  example-crates/example_electrum/src/main.rs
  example-crates/wallet_electrum/src/main.rs
Labels: module-blockchain, api

#1437 Bump bdk version to 1.0.0-alpha.11
  crates/bdk/Cargo.toml
  crates/bitcoind_rpc/Cargo.toml
  crates/chain/Cargo.toml
  crates/electrum/Cargo.toml
  crates/esplora/Cargo.toml
  crates/file_store/Cargo.toml
  crates/persist/Cargo.toml
  crates/testenv/Cargo.toml
Labels: release

#1326 chore: rename bdk crate to bdk_wallet
  .github/workflows/cont_integration.yml
  Cargo.toml
  README.md
  crates/hwi/Cargo.toml
  crates/hwi/src/lib.rs
  crates/hwi/src/signer.rs
  crates/wallet/Cargo.toml
  crates/wallet/README.md
  crates/wallet/examples/compiler.rs
  crates/wallet/examples/mnemonic_to_descriptors.rs
  crates/wallet/examples/policy.rs
  crates/wallet/src/descriptor/checksum.rs
  crates/wallet/src/descriptor/dsl.rs
  crates/wallet/src/descriptor/error.rs
  crates/wallet/src/descriptor/mod.rs
  crates/wallet/src/descriptor/policy.rs
  crates/wallet/src/descriptor/template.rs
  crates/wallet/src/keys/bip39.rs
  crates/wallet/src/keys/mod.rs
  crates/wallet/src/lib.rs
  crates/wallet/src/psbt/mod.rs
  crates/wallet/src/types.rs
  crates/wallet/src/wallet/coin_selection.rs
  crates/wallet/src/wallet/error.rs
  crates/wallet/src/wallet/export.rs
  crates/wallet/src/wallet/hardwaresigner.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/src/wallet/signer.rs
  crates/wallet/src/wallet/tx_builder.rs
  crates/wallet/src/wallet/utils.rs
  crates/wallet/tests/common.rs
  crates/wallet/tests/psbt.rs
  crates/wallet/tests/wallet.rs
  example-crates/wallet_electrum/Cargo.toml
  example-crates/wallet_electrum/src/main.rs
  example-crates/wallet_esplora_async/Cargo.toml
  example-crates/wallet_esplora_async/src/main.rs
  example-crates/wallet_esplora_blocking/Cargo.toml
  example-crates/wallet_esplora_blocking/src/main.rs
  example-crates/wallet_rpc/Cargo.toml
  example-crates/wallet_rpc/README.md
  example-crates/wallet_rpc/src/main.rs
Labels: module-wallet, api

#1443 fix(electrum): Fix `fetch_prev_txout`
  crates/electrum/src/electrum_ext.rs
Labels: bug

#1128 feat: add bdk_sqlite crate implementing PersistBackend
  .github/workflows/nightly_docs.yml
  .gitignore
  Cargo.toml
  README.md
  crates/bitcoind_rpc/Cargo.toml
  crates/chain/src/lib.rs
  crates/esplora/Cargo.toml
  crates/file_store/README.md
  crates/persist/Cargo.toml
  crates/persist/README.md
  crates/persist/src/changeset.rs
  crates/persist/src/lib.rs
  crates/sqlite/Cargo.toml
  crates/sqlite/README.md
  crates/sqlite/schema/schema_0.sql
  crates/sqlite/src/lib.rs
  crates/sqlite/src/schema.rs
  crates/sqlite/src/store.rs
  crates/wallet/Cargo.toml
  crates/wallet/src/wallet/mod.rs
  crates/wallet/tests/wallet.rs
  example-crates/wallet_esplora_async/Cargo.toml
  example-crates/wallet_esplora_async/src/main.rs
  nursery/coin_select/src/bnb.rs
Labels: enhancement, module-database

#1386 Remove TxBuilder allow_shrinking() and unneeded context param
  crates/wallet/src/wallet/mod.rs
  crates/wallet/src/wallet/tx_builder.rs
  crates/wallet/tests/wallet.rs
Labels: bug, module-wallet, api

#1393 fix(export): add tr descriptor
  crates/wallet/src/wallet/export.rs
Labels: module-wallet

#1450 Bump bdk version to 1.0.0-alpha.12
  crates/bitcoind_rpc/Cargo.toml
  crates/chain/Cargo.toml
  crates/electrum/Cargo.toml
  crates/esplora/Cargo.toml
  crates/file_store/Cargo.toml
  crates/hwi/Cargo.toml
  crates/hwi/README.md
  crates/persist/Cargo.toml
  crates/sqlite/Cargo.toml
  crates/testenv/Cargo.toml
  crates/wallet/Cargo.toml
Labels: release
