Repository bitcoindevkit/bdk, pull requests merged in 2024-12, with the labels that each got.

#1733 feat(chain,wallet)!: Transitive `ChainPosition`
  crates/chain/src/chain_data.rs
  crates/chain/src/tx_graph.rs
  crates/chain/tests/test_indexed_tx_graph.rs
  crates/chain/tests/test_tx_graph.rs
  crates/wallet/src/test_utils.rs
  crates/wallet/src/wallet/coin_selection.rs
  crates/wallet/src/wallet/export.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/src/wallet/tx_builder.rs
  crates/wallet/tests/wallet.rs
Labels: module-blockchain, api

#1751 deps(electrum): bump `electrum-client` to 0.22.0
  crates/electrum/Cargo.toml
Labels: dependencies

#1737 fix(tx_builder)!: make TxBuilder Send safe, remove Clone trait
  crates/wallet/src/wallet/mod.rs
  crates/wallet/src/wallet/tx_builder.rs
  crates/wallet/tests/wallet.rs
Labels: module-wallet, api

#1746 deps(esplora): bump `esplora-client` to 0.11.0
  crates/esplora/Cargo.toml
  crates/esplora/README.md
  crates/esplora/src/async_ext.rs
  example-crates/example_wallet_esplora_async/Cargo.toml
Labels: dependencies

#1756 fix(electrum): prevent `fetch_prev_txout` from querying coinbase transactions
  crates/electrum/src/bdk_electrum_client.rs
  crates/electrum/tests/test_electrum.rs
Labels: bug, audit

#1752 Remove serde json dependency from chain crate
  crates/chain/Cargo.toml
  crates/chain/src/lib.rs
  crates/chain/src/rusqlite_impl.rs
  crates/wallet/src/wallet/changeset.rs
  crates/wallet/tests/wallet.rs
Labels: module-database, dependencies

#1670 Introduce `O(n)` canonicalization algorithm
  .github/workflows/cont_integration.yml
  README.md
  crates/bitcoind_rpc/tests/test_emitter.rs
  crates/chain/Cargo.toml
  crates/chain/benches/canonicalization.rs
  crates/chain/src/canonical_iter.rs
  crates/chain/src/indexed_tx_graph.rs
  crates/chain/src/lib.rs
  crates/chain/src/tx_graph.rs
  crates/chain/tests/common/tx_template.rs
  crates/chain/tests/test_indexed_tx_graph.rs
  crates/chain/tests/test_tx_graph.rs
  crates/chain/tests/test_tx_graph_conflicts.rs
  crates/wallet/src/test_utils.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/tests/wallet.rs
  docs/adr/0003_canonicalization_algorithm.md
  example-crates/example_cli/src/lib.rs
Labels: bug, module-blockchain, api, audit

#1763 Change coin_selection and DescriptorExt::dust_value to use Amount type
  .github/workflows/cont_integration.yml
  README.md
  crates/chain/src/descriptor_ext.rs
  crates/wallet/src/wallet/coin_selection.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/tests/wallet.rs
  example-crates/example_cli/src/lib.rs
Labels: module-wallet, api, module-coinselection

#1772 Bump bdk_wallet version to 1.0.0-beta.6
  crates/bitcoind_rpc/Cargo.toml
  crates/chain/Cargo.toml
  crates/core/Cargo.toml
  crates/electrum/Cargo.toml
  crates/esplora/Cargo.toml
  crates/file_store/Cargo.toml
  crates/testenv/Cargo.toml
  crates/wallet/Cargo.toml
Labels: release

#1680 docs(wallet): reword the `next_unused_address` doc
  crates/wallet/src/wallet/mod.rs
Labels: documentation, module-wallet

#1774 chore[chain,wallet]: fix build warnings
  crates/chain/src/tx_graph.rs
  crates/wallet/src/wallet/changeset.rs
Labels: chore

#1779 `transactions` method should only return relevant transactions
  crates/wallet/src/wallet/mod.rs
  crates/wallet/tests/wallet.rs
Labels: bug

#1784 Bump bdk_wallet version to 1.0.0
  CHANGELOG.md
  crates/bitcoind_rpc/CHANGELOG.md
  crates/bitcoind_rpc/Cargo.toml
  crates/chain/CHANGELOG.md
  crates/chain/Cargo.toml
  crates/core/CHANGELOG.md
  crates/core/Cargo.toml
  crates/electrum/CHANGELOG.md
  crates/electrum/Cargo.toml
  crates/esplora/CHANGELOG.md
  crates/esplora/Cargo.toml
  crates/file_store/CHANGELOG.md
  crates/file_store/Cargo.toml
  crates/testenv/CHANGELOG.md
  crates/testenv/Cargo.toml
  crates/wallet/CHANGELOG.md
  crates/wallet/Cargo.toml
Labels: release

#1785 test(wallet): small cleanups to test_wallet_transactions_relevant
  crates/wallet/src/wallet/mod.rs
  crates/wallet/tests/wallet.rs
Labels: tests

#1768 refactor(wallet): cleanup and remove unused code in create_tx
  crates/wallet/src/wallet/mod.rs
Labels: module-wallet, audit
