Repository bitcoindevkit/bdk, pull requests merged in 2024-03, with the labels that each got.

#1349 Fix `KeychainTxOutIndex::lookahead_to_target`
  crates/chain/src/keychain/txout_index.rs
  crates/chain/tests/test_keychain_txout_index.rs
Labels: bug

#1365 Bump bdk version to 1.0.0-alpha.7
  crates/bdk/Cargo.toml
  crates/bitcoind_rpc/Cargo.toml
  crates/chain/Cargo.toml
  crates/electrum/Cargo.toml
  crates/esplora/Cargo.toml
  crates/file_store/Cargo.toml
Labels: release

#1216 Migrate to bitcoin::FeeRate
  crates/bdk/src/psbt/mod.rs
  crates/bdk/src/types.rs
  crates/bdk/src/wallet/coin_selection.rs
  crates/bdk/src/wallet/error.rs
  crates/bdk/src/wallet/hardwaresigner.rs
  crates/bdk/src/wallet/mod.rs
  crates/bdk/src/wallet/tx_builder.rs
  crates/bdk/tests/common.rs
  crates/bdk/tests/psbt.rs
  crates/bdk/tests/wallet.rs
  crates/hwi/src/lib.rs
Labels: module-wallet, api

#1310 Remove extra taproot fields when finalizing PSBT
  crates/bdk/src/wallet/mod.rs
  crates/bdk/src/wallet/signer.rs
  crates/bdk/tests/psbt.rs
  crates/bdk/tests/wallet.rs
Labels: bug, module-wallet

#1378 Update bdk README
  crates/bdk/README.md
Labels: documentation

#1171 chore: extract `TestEnv` into separate crate
  .github/workflows/nightly_docs.yml
  Cargo.toml
  crates/bitcoind_rpc/Cargo.toml
  crates/bitcoind_rpc/tests/test_emitter.rs
  crates/electrum/Cargo.toml
  crates/electrum/src/electrum_ext.rs
  crates/electrum/tests/test_electrum.rs
  crates/esplora/Cargo.toml
  crates/esplora/tests/async_ext.rs
  crates/esplora/tests/blocking_ext.rs
  crates/testenv/Cargo.toml
  crates/testenv/README.md
  crates/testenv/src/lib.rs
Labels: tests, module-blockchain

#1351 fix: define and document `stop_gap`
  crates/esplora/src/async_ext.rs
  crates/esplora/src/blocking_ext.rs
  crates/esplora/tests/async_ext.rs
  crates/esplora/tests/blocking_ext.rs
Labels: module-blockchain, api

#1389 Bump bdk version to 1.0.0-alpha.8
  crates/bdk/Cargo.toml
  crates/bitcoind_rpc/Cargo.toml
  crates/electrum/Cargo.toml
  crates/esplora/Cargo.toml
  crates/file_store/Cargo.toml
  crates/hwi/Cargo.toml
Labels: release

#1373 Wrap transactions as `Arc<Transaction>` in `TxGraph`
  crates/bdk/src/wallet/mod.rs
  crates/bdk/tests/wallet.rs
  crates/chain/Cargo.toml
  crates/chain/src/tx_graph.rs
  crates/chain/tests/test_indexed_tx_graph.rs
  crates/chain/tests/test_tx_graph.rs
  crates/esplora/tests/async_ext.rs
  crates/esplora/tests/blocking_ext.rs
Labels: module-blockchain, api
