Repository bitcoindevkit/bdk, pull requests merged in 2024-09, with the labels that each got.

#1587 feat(core): add `TxUpdate::map_anchors`
  crates/core/src/tx_update.rs
Labels: enhancement

#1590 ci: pin `tokio-util` dependency version to build with rust 1.63
  .github/workflows/cont_integration.yml
  README.md
Labels: ci

#1477 feat(wallet): add transactions_sort_by function
  crates/wallet/src/wallet/mod.rs
  crates/wallet/tests/wallet.rs
Labels: enhancement, module-wallet

#1584 docs: update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#1579 fix(wallet): only mark change address used if `create_tx` succeeds
  .github/workflows/code_coverage.yml
  .github/workflows/nightly_docs.yml
  crates/wallet/src/wallet/mod.rs
  crates/wallet/tests/wallet.rs
Labels: bug

#1586 Change methods of `IndexedTxGraph`/`TxGraph`/`Wallet` that insert txs to be more generic
  crates/chain/src/indexed_tx_graph.rs
  crates/chain/src/tx_graph.rs
  crates/chain/tests/test_indexed_tx_graph.rs
  crates/wallet/src/wallet/mod.rs
  example-crates/example_bitcoind_rpc_polling/src/main.rs
  example-crates/wallet_rpc/src/main.rs
Labels: enhancement, api

#1599 fix: typos
  crates/core/src/checkpoint.rs
  crates/core/src/tx_update.rs
  crates/wallet/src/wallet/mod.rs
Labels: documentation

#1561 refactor(bdk_hwi): remove `bdk_hwi`, as `HWISigner`'s being moved to `rust-hwi`
  .github/workflows/code_coverage.yml
  Cargo.toml
  ci/Dockerfile.ledger
  ci/automation.json
  crates/hwi/Cargo.toml
  crates/hwi/README.md
  crates/hwi/src/lib.rs
  crates/hwi/src/signer.rs
  crates/wallet/src/wallet/hardwaresigner.rs
Labels: api, chore

#1581 Allow custom fallback algorithm for bnb
  crates/wallet/src/wallet/coin_selection.rs
  crates/wallet/src/wallet/error.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/tests/wallet.rs
Labels: enhancement, discussion, api

#1601 fix(core): calling `CheckPoint::insert` with existing block must succeed
  crates/core/src/checkpoint.rs
  crates/core/tests/common.rs
  crates/core/tests/test_checkpoint.rs
Labels: bug

#1605 fix(wallet): fix SingleRandomDraw to error if insufficient funds
  crates/wallet/src/wallet/coin_selection.rs
Labels: bug

#1608 Bump bdk_wallet version to 1.0.0-beta.3
  crates/bitcoind_rpc/Cargo.toml
  crates/chain/Cargo.toml
  crates/core/Cargo.toml
  crates/electrum/Cargo.toml
  crates/esplora/Cargo.toml
  crates/file_store/Cargo.toml
  crates/testenv/Cargo.toml
  crates/wallet/Cargo.toml
Labels: release

#1610 Bump bdk_wallet version to 1.0.0-beta.4
  crates/bitcoind_rpc/Cargo.toml
  crates/chain/Cargo.toml
  crates/core/Cargo.toml
  crates/electrum/Cargo.toml
  crates/esplora/Cargo.toml
  crates/file_store/Cargo.toml
  crates/testenv/Cargo.toml
  crates/wallet/Cargo.toml
Labels: release

#1603 fix(RUSTSEC-2024-0370): proc-macro-error is unmaintained
  .github/workflows/cont_integration.yml
  Cargo.toml
  crates/electrum/Cargo.toml
  crates/esplora/Cargo.toml
  crates/esplora/README.md
  example-crates/example_cli/Cargo.toml
  example-crates/example_wallet_electrum/Cargo.toml
  example-crates/example_wallet_electrum/src/main.rs
  example-crates/example_wallet_esplora_async/Cargo.toml
  example-crates/example_wallet_esplora_async/src/main.rs
  example-crates/example_wallet_esplora_blocking/Cargo.toml
  example-crates/example_wallet_esplora_blocking/src/main.rs
  example-crates/example_wallet_rpc/Cargo.toml
  example-crates/example_wallet_rpc/README.md
  example-crates/example_wallet_rpc/src/main.rs
Labels: ci, dependencies

#1623 fix!(wallet): `ChangeSet` should not be non-exhaustive
  crates/wallet/src/wallet/changeset.rs
Labels: module-wallet

#1616 feat(wallet)!: enable RBF by default on TxBuilder
  crates/wallet/README.md
  crates/wallet/src/wallet/error.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/src/wallet/tx_builder.rs
  crates/wallet/src/wallet/utils.rs
  crates/wallet/tests/wallet.rs
  example-crates/example_wallet_electrum/src/main.rs
  example-crates/example_wallet_esplora_async/src/main.rs
  example-crates/example_wallet_esplora_blocking/src/main.rs
Labels: module-wallet, api
