Repository bitcoindevkit/bdk, pull requests merged in 2024-11, with the labels that each got.

#1674 ci: pin deps for MSRV
  .github/workflows/cont_integration.yml
  README.md
Labels: ci

#1724 Type constraint on list canonical tx
  crates/chain/src/tx_graph.rs
Labels: module-blockchain, audit

#1722 fix(testenv): disable downloads (bitcoind and electrsd) for docs.rs b…
  crates/bitcoind_rpc/Cargo.toml
  crates/electrum/Cargo.toml
  crates/esplora/Cargo.toml
  crates/testenv/Cargo.toml
Labels: documentation, release

#1727 Use `bitcoin::constants::COINBASE_MATURITY`
  crates/chain/src/chain_data.rs
  crates/chain/src/lib.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/tests/wallet.rs
Labels: module-blockchain, api, audit

#1732 chore(core)!: rename `SyncResult` to `SyncResponse`
  crates/core/src/spk_client.rs
  crates/electrum/src/bdk_electrum_client.rs
  crates/electrum/src/lib.rs
  crates/electrum/tests/test_electrum.rs
  crates/esplora/src/async_ext.rs
  crates/esplora/src/blocking_ext.rs
  crates/wallet/src/wallet/mod.rs
Labels: module-blockchain, api

#1731 fix(core): Fix checkpoint Drop stack overflow
  crates/core/src/checkpoint.rs
  crates/core/tests/test_checkpoint.rs
Labels: bug, module-blockchain

#1681 types: Make Utxo::Foreign::sequence not optional
  crates/wallet/src/types.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/src/wallet/tx_builder.rs
Labels: module-wallet, api

#1730 Check time when persisting in `rusqlite` impl
  crates/chain/src/rusqlite_impl.rs
Labels: module-database, audit

#1721 chore(deps): bump hashbrown to v0.14.5
  crates/core/Cargo.toml
Labels: dependencies

#1734 chore(chain)!: use `debug_assert!` on `apply_update`
  crates/chain/src/local_chain.rs
Labels: module-blockchain, audit

#1744 test: update electrsd to fix RUSTSEC-2024-0384 warning
  Cargo.toml
Labels: tests, ci

#1736 Sqlite - allow persisting anchor without tx
  crates/chain/src/rusqlite_impl.rs
  crates/chain/tests/test_tx_graph.rs
Labels: module-database, audit

#1749 chore: Revert `rustls` pin dependency
  .github/workflows/cont_integration.yml
  README.md
Labels: ci, dependencies, chore
