Repository bitcoindevkit/bdk, pull requests merged in 2024-08, with the labels that each got.

#1529 fix: typos
  crates/chain/src/persist.rs
  crates/wallet/src/wallet/params.rs
  crates/wallet/src/wallet/persisted.rs
Labels: ci

#1530 chore: fix clippy lints
  crates/chain/src/indexer/spk_txout.rs
  crates/wallet/src/wallet/changeset.rs
  crates/wallet/src/wallet/tx_builder.rs
Labels: ci

#1523 bdk_wallet: Don't reimplement descriptor checksum, use the one from rust-miniscript
  crates/wallet/src/descriptor/checksum.rs
  crates/wallet/src/descriptor/mod.rs
  crates/wallet/src/wallet/mod.rs
Labels: module-wallet

#1544 Remove crate-renaming
  crates/chain/Cargo.toml
  crates/chain/src/balance.rs
  crates/chain/src/chain_data.rs
  crates/chain/src/indexed_tx_graph.rs
  crates/chain/src/indexer/keychain_txout.rs
  crates/chain/src/lib.rs
  crates/chain/src/local_chain.rs
  crates/chain/src/rusqlite_impl.rs
  crates/chain/src/tx_graph.rs
Labels: dependencies

#1494 Add documentation for Electrum's full_scan/sync
  crates/electrum/src/bdk_electrum_client.rs
Labels: documentation

#1491 Enable selecting use-rustls-ring feature on electrum client
  crates/electrum/Cargo.toml
Labels: module-blockchain

#1533 [wallet] Enable support for single descriptor wallets
  crates/chain/src/lib.rs
  crates/wallet/README.md
  crates/wallet/examples/compiler.rs
  crates/wallet/src/wallet/changeset.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/src/wallet/params.rs
  crates/wallet/src/wallet/tx_builder.rs
  crates/wallet/tests/wallet.rs
  example-crates/wallet_electrum/src/main.rs
  example-crates/wallet_esplora_async/src/main.rs
  example-crates/wallet_esplora_blocking/src/main.rs
  example-crates/wallet_rpc/src/main.rs
Labels: module-wallet, api

#1478 Allow opting out of getting `LocalChain` updates with `FullScanRequest`/`SyncRequest` structures
  crates/chain/src/spk_client.rs
  crates/electrum/src/bdk_electrum_client.rs
  crates/electrum/tests/test_electrum.rs
  crates/esplora/Cargo.toml
  crates/esplora/README.md
  crates/esplora/src/async_ext.rs
  crates/esplora/src/blocking_ext.rs
  crates/esplora/src/lib.rs
  crates/esplora/tests/async_ext.rs
  crates/esplora/tests/blocking_ext.rs
  crates/wallet/src/wallet/mod.rs
  example-crates/example_electrum/src/main.rs
  example-crates/example_esplora/src/main.rs
  example-crates/wallet_electrum/src/main.rs
  example-crates/wallet_esplora_async/src/main.rs
  example-crates/wallet_esplora_blocking/src/main.rs
Labels: module-blockchain

#1537 Use explicit names for wallet builder methods that validate rather than set
  crates/wallet/README.md
  crates/wallet/src/wallet/mod.rs
  crates/wallet/src/wallet/params.rs
  crates/wallet/tests/wallet.rs
  example-crates/wallet_electrum/src/main.rs
  example-crates/wallet_esplora_async/src/main.rs
  example-crates/wallet_esplora_blocking/src/main.rs
  example-crates/wallet_rpc/src/main.rs
Labels: api

#1549 fix(example_cli): add bitcoin and rand dependencies
  .github/workflows/cont_integration.yml
  example-crates/example_cli/Cargo.toml
  example-crates/example_cli/src/lib.rs
Labels: documentation, ci

#1547 Simplify wallet persistence
  crates/chain/src/lib.rs
  crates/chain/src/persist.rs
  crates/chain/src/rusqlite_impl.rs
  crates/wallet/src/wallet/changeset.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/src/wallet/params.rs
  crates/wallet/src/wallet/persisted.rs
  crates/wallet/tests/wallet.rs
Labels: module-database

#1560 Derive `Clone` on `AddressInfo`
  crates/wallet/src/wallet/mod.rs
Labels: module-wallet

#1562 fix(wallet)!: make `LoadParams` implicitly satisfy `Send`
  crates/wallet/src/wallet/mod.rs
  crates/wallet/src/wallet/params.rs
Labels: module-database

#1564 ci: add cron-update-rust.yml
  .github/workflows/cont_integration.yml
  .github/workflows/cron-update-rust.yml
  rust-version
Labels: ci

#1568 Introduce `tx_graph::Update` and simplify `TxGraph` update logic
  crates/chain/src/indexed_tx_graph.rs
  crates/chain/src/lib.rs
  crates/chain/src/spk_client.rs
  crates/chain/src/tx_graph.rs
  crates/chain/tests/test_tx_graph.rs
  crates/electrum/src/bdk_electrum_client.rs
  crates/electrum/tests/test_electrum.rs
  crates/esplora/src/async_ext.rs
  crates/esplora/src/blocking_ext.rs
  crates/esplora/src/lib.rs
  crates/esplora/tests/async_ext.rs
  crates/esplora/tests/blocking_ext.rs
  crates/wallet/src/wallet/export.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/tests/common.rs
  crates/wallet/tests/wallet.rs
  example-crates/example_electrum/src/main.rs
  example-crates/example_esplora/src/main.rs
  example-crates/wallet_electrum/src/main.rs
  example-crates/wallet_esplora_async/src/main.rs
  example-crates/wallet_esplora_blocking/src/main.rs
Labels: module-blockchain, api

#1569 Introduce `bdk_core`
  Cargo.toml
  crates/bitcoind_rpc/Cargo.toml
  crates/bitcoind_rpc/src/lib.rs
  crates/chain/Cargo.toml
  crates/chain/src/chain_data.rs
  crates/chain/src/example_utils.rs
  crates/chain/src/indexed_tx_graph.rs
  crates/chain/src/indexer/keychain_txout.rs
  crates/chain/src/lib.rs
  crates/chain/src/local_chain.rs
  crates/chain/src/rusqlite_impl.rs
  crates/chain/src/tx_data_traits.rs
  crates/chain/src/tx_graph.rs
  crates/chain/tests/test_tx_graph.rs
  crates/core/Cargo.toml
  crates/core/src/block_id.rs
  crates/core/src/checkpoint.rs
  crates/core/src/lib.rs
  crates/core/src/spk_client.rs
  crates/core/src/tx_update.rs
  crates/electrum/Cargo.toml
  crates/electrum/src/bdk_electrum_client.rs
  crates/electrum/src/lib.rs
  crates/electrum/tests/test_electrum.rs
  crates/esplora/Cargo.toml
  crates/esplora/README.md
  crates/esplora/src/async_ext.rs
  crates/esplora/src/blocking_ext.rs
  crates/esplora/src/lib.rs
  crates/esplora/tests/async_ext.rs
  crates/esplora/tests/blocking_ext.rs
  crates/wallet/src/wallet/export.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/tests/common.rs
  crates/wallet/tests/wallet.rs
  example-crates/example_cli/src/lib.rs
  example-crates/example_electrum/src/main.rs
  example-crates/example_esplora/src/main.rs
  example-crates/wallet_electrum/src/main.rs
Labels: module-blockchain, api

#1573 chore: add missing bdk_core README.md and remove specific bdk_chain dev version
  crates/core/Cargo.toml
  crates/core/README.md
Labels: chore

#1425 chore: add `print_stdout`/`print_stderr` lints to workspace level
  Cargo.toml
  clippy.toml
  crates/bitcoind_rpc/Cargo.toml
  crates/bitcoind_rpc/tests/test_emitter.rs
  crates/chain/Cargo.toml
  crates/chain/tests/test_local_chain.rs
  crates/electrum/Cargo.toml
  crates/esplora/Cargo.toml
  crates/esplora/src/async_ext.rs
  crates/esplora/src/blocking_ext.rs
  crates/file_store/Cargo.toml
  crates/file_store/src/store.rs
  crates/hwi/Cargo.toml
  crates/testenv/Cargo.toml
  crates/wallet/Cargo.toml
  crates/wallet/examples/compiler.rs
  crates/wallet/examples/mnemonic_to_descriptors.rs
  crates/wallet/examples/policy.rs
  crates/wallet/src/wallet/coin_selection.rs
Labels: ci

#1580 ci: add token for cron-update-rust.yml
  .github/workflows/cron-update-rust.yml
Labels: ci
