Repository bitcoindevkit/bdk, pull requests merged in 2025-03, with the labels that each got.

#1867 fix(ci): pin `bzip2-sys` to `0.1.12`
  .github/workflows/code_coverage.yml
  ci/pin-msrv.sh
Labels: ci

#1798 Refactor/use iterators to preselect utxos
  crates/wallet/src/wallet/coin_selection.rs
  crates/wallet/src/wallet/mod.rs
  crates/wallet/src/wallet/tx_builder.rs
Labels: module-wallet

#1684 Refactor file store
  README.md
  crates/file_store/src/entry_iter.rs
  crates/file_store/src/lib.rs
  crates/file_store/src/store.rs
  example-crates/example_bitcoind_rpc_polling/src/main.rs
  example-crates/example_cli/src/lib.rs
  example-crates/example_electrum/src/main.rs
  example-crates/example_esplora/src/main.rs
Labels: module-database, api

#1871 docs: update CONTRIBUTING.md with section for new contributors
  CONTRIBUTING.md
Labels: documentation

#1872 fix(examples): make regtest default on wallet_example_rpc
  example-crates/example_wallet_rpc/README.md
  example-crates/example_wallet_rpc/src/main.rs
Labels: documentation

#1876 ci: pin `ring` to `0.17.12` for MSRV 1.63
  ci/pin-msrv.sh
Labels: ci

#1865 chore(examples): make change descriptor optional on example_wallet_rpc
  example-crates/example_wallet_rpc/README.md
  example-crates/example_wallet_rpc/src/main.rs
Labels: documentation

#1841 Generalize `add_recipient` to accept `Address`
  crates/wallet/src/wallet/tx_builder.rs
Labels: module-wallet

#1883 ci: pin `once_cell` to `1.20.3` for MSRV
  ci/pin-msrv.sh
Labels: ci

#1882 doc: remove 1.0 roadmap stuff and fix broken links from README
  README.md
Labels: documentation

#1884 doc: remove persist crate from README
  README.md
Labels: documentation

#1874 fix(wallet): allow PersistedWallet to be Send + Sync
  crates/wallet/src/wallet/persisted.rs
  crates/wallet/tests/wallet.rs
Labels: bug

#1886 ci: pin `minreq` to `2.13.2`, `base64ct` to `1.6.0` for MSRV
  .github/workflows/cont_integration.yml
  ci/pin-msrv.sh
Labels: ci

#1839 Introduce `evicted-at`/`last-evicted` timestamps
  .github/workflows/cont_integration.yml
  crates/chain/src/indexed_tx_graph.rs
  crates/chain/src/indexer/keychain_txout.rs
  crates/chain/src/indexer/spk_txout.rs
  crates/chain/src/rusqlite_impl.rs
  crates/chain/src/tx_graph.rs
  crates/chain/tests/test_tx_graph.rs
  crates/core/src/spk_client.rs
  crates/core/src/tx_update.rs
  crates/electrum/src/bdk_electrum_client.rs
  crates/electrum/tests/test_electrum.rs
  crates/esplora/Cargo.toml
  crates/esplora/src/async_ext.rs
  crates/esplora/src/blocking_ext.rs
  crates/esplora/tests/async_ext.rs
  crates/esplora/tests/blocking_ext.rs
  crates/esplora/tests/common/mod.rs
  example-crates/example_electrum/src/main.rs
  example-crates/example_esplora/src/main.rs
Labels: bug, api

#1885 ci: use `ubuntu-latest` on `check-wasm`
  .github/workflows/cont_integration.yml
Labels: ci

#1895 ci: fix publish_docs job fails with "permission denied"
  .github/workflows/nightly_docs.yml
Labels: ci

#1896 ci: remove not needed nightly_docs workflow
  .github/workflows/nightly_docs.yml
Labels: ci
