Repository bitcoindevkit/bdk, pull requests merged in 2025-07, with the labels that each got.

#1957 feat(electrum): optimize merkle proof validation with batching
  crates/electrum/Cargo.toml
  crates/electrum/benches/test_sync.rs
  crates/electrum/src/bdk_electrum_client.rs
Labels: module-blockchain

#1897 test for excluded bounds in outputs_in_range
  crates/chain/tests/test_spk_txout_index.rs
Labels: tests, audit

#1999 fix(ci): pin `socket2@0.6.0` to `0.5.10` on MSRV
  ci/pin-msrv.sh
Labels: chore

#1986 ci: replace grcov by cargo-llvm-cov
  .github/workflows/code_coverage.yml
  Cargo.toml
  crates/bitcoind_rpc/src/lib.rs
  crates/chain/src/chain_data.rs
  crates/chain/src/lib.rs
  crates/chain/src/rusqlite_impl.rs
  crates/chain/src/spk_iter.rs
  crates/electrum/src/bdk_electrum_client.rs
  crates/electrum/src/lib.rs
  crates/esplora/src/async_ext.rs
  crates/esplora/src/blocking_ext.rs
  crates/esplora/src/lib.rs
  crates/file_store/src/lib.rs
  crates/file_store/src/store.rs
  crates/testenv/Cargo.toml
  crates/testenv/src/lib.rs
Labels: tests
