Repository bitcoindevkit/bdk, pull requests merged in 2025-01, with the labels that each got.

#1592 Architectural Decision Records
  docs/adr/0001_persist.md
  docs/adr/0002_persisted.md
  docs/adr/template.md
Labels: documentation

#1782 fix electrum conftime_req filter for needs_block_height
  .github/workflows/code_coverage.yml
  .github/workflows/cont_integration.yml
  .github/workflows/nightly_docs.yml
  Cargo.toml
  README.md
  examples/compiler.rs
  examples/policy.rs
  src/blockchain/electrum.rs
  src/database/keyvalue.rs
  src/database/mod.rs
  src/descriptor/mod.rs
  src/keys/mod.rs
  src/wallet/coin_selection.rs
  src/wallet/tx_builder.rs
Labels: bug

#1791 Update bdk 0.30.x README docs to deprecate the bdk library
  CHANGELOG.md
  Cargo.toml
  README.md
  src/lib.rs
Labels: documentation

#1790 fix(wallet): improve safety on finaize psbt
  crates/wallet/src/wallet/mod.rs
Labels: module-wallet

#1789 Change default tx to version 2
  crates/wallet/src/wallet/mod.rs
  crates/wallet/src/wallet/tx_builder.rs
  crates/wallet/tests/wallet.rs
Labels: module-wallet

#1685 test(electrum): test for checking that fee calculation is correct
  crates/electrum/tests/test_electrum.rs
Labels: tests

#1803 ci: add secondary MSRV job of 1.75.0
  .github/workflows/cont_integration.yml
  README.md
  ci/pin-msrv.sh
  crates/electrum/README.md
Labels: ci

#1682 test(wallet): create tx locktime cltv for a specific time
  crates/wallet/src/test_utils.rs
  crates/wallet/tests/wallet.rs
Labels: tests, module-wallet

#1805 feat(wallet): support Testnet4 in valid networks
  crates/wallet/src/descriptor/dsl.rs
  crates/wallet/src/descriptor/mod.rs
  crates/wallet/src/keys/bip39.rs
  crates/wallet/src/keys/mod.rs
Labels: new feature

#1614 feat(rpc): introduce FilterIter
  crates/bitcoind_rpc/Cargo.toml
  crates/bitcoind_rpc/examples/README.md
  crates/bitcoind_rpc/examples/filter_iter.rs
  crates/bitcoind_rpc/src/bip158.rs
  crates/bitcoind_rpc/src/lib.rs
  crates/bitcoind_rpc/tests/test_filter_iter.rs
Labels: new feature, discussion, module-blockchain

#1778 ci: apply `zizmor` security audit
  .github/workflows/audit.yml
  .github/workflows/code_coverage.yml
  .github/workflows/cont_integration.yml
  .github/workflows/cron-update-rust.yml
  .github/workflows/nightly_docs.yml
Labels: ci
