Repository bitcoindevkit/bdk, pull requests merged in 2025-05, with the labels that each got.

#1808 Introduce canonicalization parameters
  crates/bitcoind_rpc/examples/filter_iter.rs
  crates/bitcoind_rpc/tests/test_emitter.rs
  crates/chain/benches/canonicalization.rs
  crates/chain/src/canonical_iter.rs
  crates/chain/src/tx_graph.rs
  crates/chain/tests/common/tx_template.rs
  crates/chain/tests/test_indexed_tx_graph.rs
  crates/chain/tests/test_tx_graph.rs
  crates/chain/tests/test_tx_graph_conflicts.rs
  crates/electrum/tests/test_electrum.rs
  examples/example_bitcoind_rpc_polling/src/main.rs
  examples/example_cli/src/lib.rs
  examples/example_electrum/src/main.rs
  examples/example_esplora/src/main.rs
Labels: api

#1857 feat(rpc)!: Update `Emitter::mempool` to support `evicted_at`
  crates/bitcoind_rpc/src/lib.rs
  crates/bitcoind_rpc/tests/test_emitter.rs
  crates/chain/src/chain_data.rs
  crates/chain/src/indexed_tx_graph.rs
  crates/chain/src/tx_graph.rs
  examples/example_bitcoind_rpc_polling/src/main.rs
Labels: new feature, api

#1950 feat!(chain): implement `first_seen` tracking
  crates/chain/src/chain_data.rs
  crates/chain/src/tx_graph.rs
  crates/chain/tests/test_indexed_tx_graph.rs
  crates/chain/tests/test_tx_graph.rs
Labels: api

#1806 fix(docs): `merge_chains` outdated documentation
  crates/chain/src/local_chain.rs
Labels: documentation

#1955 chore: Update rust-version to 1.86.0
  crates/chain/src/tx_graph.rs
  crates/electrum/src/bdk_electrum_client.rs
  rust-version
Labels: chore

#1813 Add zizmor github actions security analysis workflow
  .github/workflows/code_coverage.yml
  .github/workflows/cont_integration.yml
  .github/workflows/cron-update-rust.yml
  .github/workflows/zizmor.yml
Labels: github_actions

#1946 chore: create and apply rustfmt.toml
  .github/pull_request_template.md
  .github/workflows/cont_integration.yml
  crates/bitcoind_rpc/src/lib.rs
  crates/chain/src/indexed_tx_graph.rs
  crates/chain/src/indexer/keychain_txout.rs
  crates/chain/src/indexer/spk_txout.rs
  crates/chain/src/lib.rs
  crates/chain/src/local_chain.rs
  crates/chain/src/spk_iter.rs
  crates/chain/src/tx_graph.rs
  crates/chain/tests/test_tx_graph.rs
  crates/core/src/checkpoint.rs
  crates/core/src/spk_client.rs
  crates/core/src/tx_update.rs
  crates/electrum/src/bdk_electrum_client.rs
  crates/esplora/src/async_ext.rs
  crates/esplora/src/blocking_ext.rs
  crates/file_store/src/store.rs
  examples/example_cli/src/lib.rs
  examples/example_electrum/src/main.rs
  rustfmt.toml
Labels: chore

#1970 chore: bump `bdk_chain` to 0.23.0
  crates/bitcoind_rpc/CHANGELOG.md
  crates/bitcoind_rpc/Cargo.toml
  crates/chain/CHANGELOG.md
  crates/chain/Cargo.toml
  crates/core/CHANGELOG.md
  crates/core/Cargo.toml
  crates/electrum/CHANGELOG.md
  crates/electrum/Cargo.toml
  crates/esplora/CHANGELOG.md
  crates/esplora/Cargo.toml
  crates/file_store/CHANGELOG.md
  crates/file_store/Cargo.toml
  crates/testenv/CHANGELOG.md
  crates/testenv/Cargo.toml
Labels: release
