Repository bitcoindevkit/bdk, pull requests merged in 2025-02, with the labels that each got.

#1738 test(core): add unit tests for `merge` trait
  crates/core/tests/test_merge.rs
Labels: tests, module-blockchain

#1822 Bump bdk_wallet to v1.1.0
  crates/bitcoind_rpc/CHANGELOG.md
  crates/bitcoind_rpc/Cargo.toml
  crates/core/CHANGELOG.md
  crates/electrum/CHANGELOG.md
  crates/electrum/Cargo.toml
  crates/wallet/CHANGELOG.md
  crates/wallet/Cargo.toml
Labels: release

#1829 ci: remove `cc` pin to fix CI error
  ci/pin-msrv.sh
Labels: ci

#1831 Fix out of memory issue caused by many txs.
  .github/workflows/cont_integration.yml
  README.md
  src/blockchain/electrum.rs
Labels: bug

#1837 `bdk_electrum`: Handle negative heights properly
  crates/electrum/src/bdk_electrum_client.rs
  crates/electrum/tests/test_electrum.rs
Labels: bug

#1853 wallet: Bump bitcoin dependency to v0.32.4
  crates/wallet/Cargo.toml
Labels: dependencies

#1859 ci: pin idna_adapter dep to fix reqest with MSRV 1.75
  .github/workflows/cont_integration.yml
Labels: ci

#1860 `bdk_wallet`: Pin `bdk_chain` version to latest release
  .github/workflows/cont_integration.yml
  crates/wallet/Cargo.toml
  example-crates/example_wallet_electrum/Cargo.toml
  example-crates/example_wallet_esplora_async/Cargo.toml
  example-crates/example_wallet_esplora_blocking/Cargo.toml
  example-crates/example_wallet_rpc/Cargo.toml
Labels: ci, chore

#1838 Make full-scan/sync flow easier to reason about.
  crates/chain/benches/canonicalization.rs
  crates/chain/src/indexed_tx_graph.rs
  crates/chain/src/tx_graph.rs
  crates/chain/tests/test_tx_graph.rs
  crates/core/src/spk_client.rs
  crates/core/src/tx_update.rs
  crates/electrum/src/bdk_electrum_client.rs
  crates/electrum/tests/test_electrum.rs
  crates/esplora/src/async_ext.rs
  crates/esplora/src/blocking_ext.rs
  crates/esplora/src/lib.rs
Labels: api
