Repository bitcoindevkit/bdk, pull requests merged in 2025-09, with the labels that each got.

#2000 `FilterIter` API redesign
  crates/bitcoind_rpc/examples/filter_iter.rs
  crates/bitcoind_rpc/src/bip158.rs
  crates/bitcoind_rpc/tests/test_filter_iter.rs
Labels: bug

#1582 refactor!: Implement generics for `CheckPoint`, `LocalChain`, and `spk_client` types
  crates/bitcoind_rpc/examples/filter_iter.rs
  crates/bitcoind_rpc/src/bip158.rs
  crates/bitcoind_rpc/src/lib.rs
  crates/bitcoind_rpc/tests/test_emitter.rs
  crates/bitcoind_rpc/tests/test_filter_iter.rs
  crates/chain/benches/canonicalization.rs
  crates/chain/benches/indexer.rs
  crates/chain/src/local_chain.rs
  crates/chain/src/tx_data_traits.rs
  crates/chain/src/tx_graph.rs
  crates/chain/tests/test_indexed_tx_graph.rs
  crates/chain/tests/test_local_chain.rs
  crates/chain/tests/test_tx_graph_conflicts.rs
  crates/core/src/checkpoint.rs
  crates/core/src/spk_client.rs
  crates/core/tests/test_checkpoint.rs
  crates/electrum/benches/test_sync.rs
  crates/electrum/src/bdk_electrum_client.rs
  crates/electrum/tests/test_electrum.rs
  crates/esplora/src/async_ext.rs
  crates/esplora/src/blocking_ext.rs
  crates/esplora/tests/async_ext.rs
  crates/esplora/tests/blocking_ext.rs
  crates/testenv/src/lib.rs
  examples/example_cli/src/lib.rs
Labels: new feature, module-blockchain, api

#2047 fix(ci): remove retry/retry-delay
  .github/workflows/code_coverage.yml
Labels: bug, github_actions
